Fix broken SQL query in allResourcesQuery
Summary: The regression was introduced by D22717

Test Plan:
compile
Launch systemsettings
No more logs: `kf5.kactivity.stat: SQL:
    error:  QSqlError` in terminal

Reviewers: ivan, #frameworks

Reviewed By: ivan

Subscribers: kde-frameworks-devel

Tags: #frameworks

Differential Revision: https://phabricator.kde.org/D26798